/**
 * Thox Imagine - Node.js/TypeScript Integration Example
 *
 * © 2026 Thox.ai LLC. All Rights Reserved.
 *
 * This example demonstrates how to integrate Thox Imagine
 * image generation into Node.js applications.
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import * as fs from 'fs/promises';
import * as path from 'path';

const execAsync = promisify(exec);

/**
 * Configuration for Thox Imagine model
 */
interface ThoxImagineConfig {
  modelName: string;
  outputDir: string;
  defaultTemperature: number;
  defaultTopP: number;
  watermark: string;
}

/**
 * Image generation options
 */
interface GenerateOptions {
  temperature?: number;
  topP?: number;
  outputPath?: string;
}

/**
 * Image generation result
 */
interface GenerationResult {
  success: boolean;
  imagePath?: string;
  error?: string;
  prompt: string;
  timestamp: Date;
}

/**
 * Thox Imagine API Client for Node.js
 */
class ThoxImagineClient {
  private config: ThoxImagineConfig = {
    modelName: 'Thox-ai/thox-imagine',
    outputDir: 'thox-imagine-outputs',
    defaultTemperature: 0.8,
    defaultTopP: 0.95,
    watermark: '© 2026 Thox.ai LLC. All Rights Reserved. Generated by Thox Imagine.',
  };

  constructor(config?: Partial<ThoxImagineConfig>) {
    if (config) {
      this.config = { ...this.config, ...config };
    }
    this.ensureOutputDir();
  }

  /**
   * Ensure output directory exists
   */
  private async ensureOutputDir(): Promise<void> {
    try {
      await fs.mkdir(this.config.outputDir, { recursive: true });
    } catch (error) {
      console.error('Failed to create output directory:', error);
    }
  }

  /**
   * Verify that the Thox Imagine model is available
   */
  async verifyModel(): Promise<boolean> {
    try {
      const { stdout } = await execAsync('ollama list');

      if (!stdout.toLowerCase().includes(this.config.modelName.toLowerCase())) {
        throw new Error(
          `Model '${this.config.modelName}' not found. ` +
          'Please create it first with: ' +
          'ollama create Thox-ai/thox-imagine -f Modelfile.thox-imagine'
        );
      }

      return true;
    } catch (error) {
      throw new Error(`Failed to verify model: ${error}`);
    }
  }

  /**
   * Generate an image from a text prompt
   *
   * @param prompt - Text description of the desired image
   * @param options - Generation options
   * @returns Generation result with image path
   *
   * @example
   * ```typescript
   * const client = new ThoxImagineClient();
   * const result = await client.generate('A serene mountain landscape');
   * console.log('Image saved to:', result.imagePath);
   * ```
   */
  async generate(
    prompt: string,
    options: GenerateOptions = {}
  ): Promise<GenerationResult> {
    const startTime = new Date();

    try {
      if (!prompt || !prompt.trim()) {
        throw new Error('Prompt cannot be empty');
      }

      // Verify model availability
      await this.verifyModel();

      console.log('🎨 Generating image with Thox Imagine...');
      console.log('📝 Prompt:', prompt);

      // Generate output path
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      const outputPath = options.outputPath ||
        path.join(this.config.outputDir, `thox_imagine_${timestamp}.png`);

      // Run ollama generate command
      const command = `ollama run ${this.config.modelName} "${prompt}"`;

      await execAsync(command);

      console.log('✅ Image generated successfully!');
      console.log('🔒 Watermark:', this.config.watermark);
      console.log('💾 Saved to:', outputPath);

      return {
        success: true,
        imagePath: outputPath,
        prompt,
        timestamp: startTime,
      };

    } catch (error) {
      console.error('❌ Image generation failed:', error);

      return {
        success: false,
        error: error instanceof Error ? error.message : String(error),
        prompt,
        timestamp: startTime,
      };
    }
  }

  /**
   * Generate multiple images from an array of prompts
   *
   * @param prompts - Array of text prompts
   * @returns Array of generation results
   *
   * @example
   * ```typescript
   * const client = new ThoxImagineClient();
   * const prompts = [
   *   'A sunset over the ocean',
   *   'A futuristic city',
   *   'An ancient forest'
   * ];
   * const results = await client.batchGenerate(prompts);
   * console.log(`Generated ${results.length} images`);
   * ```
   */
  async batchGenerate(prompts: string[]): Promise<GenerationResult[]> {
    console.log(`🚀 Starting batch generation of ${prompts.length} images...`);

    const results: GenerationResult[] = [];

    for (let i = 0; i < prompts.length; i++) {
      console.log(`\n📊 Progress: ${i + 1}/${prompts.length}`);

      try {
        const result = await this.generate(prompts[i]);
        results.push(result);
      } catch (error) {
        console.error(`Failed to generate image ${i + 1}:`, error);
        results.push({
          success: false,
          error: error instanceof Error ? error.message : String(error),
          prompt: prompts[i],
          timestamp: new Date(),
        });
      }
    }

    const successful = results.filter(r => r.success).length;
    console.log(`\n✅ Batch complete! Generated ${successful}/${prompts.length} images`);

    return results;
  }

  /**
   * Get model information
   */
  async getModelInfo(): Promise<Record<string, any>> {
    try {
      const { stdout } = await execAsync('ollama list');

      const lines = stdout.split('\n');
      const modelLine = lines.find(line =>
        line.toLowerCase().includes(this.config.modelName.toLowerCase())
      );

      if (!modelLine) {
        return { error: 'Model not found' };
      }

      return {
        name: this.config.modelName,
        base: 'x/flux2-klein',
        parameters: '8B',
        quantization: 'FP4',
        watermark: this.config.watermark,
        uncensored: true,
        organization: 'Thox.ai LLC',
      };

    } catch (error) {
      return { error: `Failed to get model info: ${error}` };
    }
  }

  /**
   * List all generated images
   */
  async listGeneratedImages(): Promise<string[]> {
    try {
      const files = await fs.readdir(this.config.outputDir);

      const imageFiles = files
        .filter(file => file.endsWith('.png'))
        .map(file => path.join(this.config.outputDir, file));

      // Sort by modification time (newest first)
      const filesWithStats = await Promise.all(
        imageFiles.map(async (file) => ({
          file,
          mtime: (await fs.stat(file)).mtime,
        }))
      );

      return filesWithStats
        .sort((a, b) => b.mtime.getTime() - a.mtime.getTime())
        .map(item => item.file);

    } catch (error) {
      console.error('Failed to list images:', error);
      return [];
    }
  }
}

/**
 * Example usage demonstrations
 */
async function examples() {
  const client = new ThoxImagineClient();

  console.log('╔════════════════════════════════════════════════════════╗');
  console.log('║    Thox Imagine - Node.js Integration Examples        ║');
  console.log('║         © 2026 Thox.ai LLC                             ║');
  console.log('╚════════════════════════════════════════════════════════╝\n');

  // Example 1: Single image generation
  console.log('Example 1: Single Image Generation');
  console.log('─'.repeat(60));
  const result1 = await client.generate(
    'A serene mountain landscape at sunset with colorful sky'
  );
  console.log('Result:', result1);

  // Example 2: Custom output path
  console.log('\n\nExample 2: Custom Output Path');
  console.log('─'.repeat(60));
  const result2 = await client.generate(
    'Futuristic cyberpunk city with neon lights',
    { outputPath: 'custom-outputs/cyberpunk-city.png' }
  );
  console.log('Result:', result2);

  // Example 3: Batch generation
  console.log('\n\nExample 3: Batch Generation');
  console.log('─'.repeat(60));
  const prompts = [
    'A peaceful zen garden',
    'An underwater coral reef scene',
    'A cozy library with warm lighting',
  ];
  const results = await client.batchGenerate(prompts);
  console.log('Batch Results:', results);

  // Example 4: Model information
  console.log('\n\nExample 4: Model Information');
  console.log('─'.repeat(60));
  const info = await client.getModelInfo();
  console.log('Model Info:', JSON.stringify(info, null, 2));

  // Example 5: List generated images
  console.log('\n\nExample 5: List Generated Images');
  console.log('─'.repeat(60));
  const images = await client.listGeneratedImages();
  console.log(`Found ${images.length} generated images:`);
  images.slice(0, 5).forEach((img, i) => {
    console.log(`  ${i + 1}. ${img}`);
  });
}

/**
 * Express.js integration example
 */
function expressExample() {
  const code = `
import express from 'express';
import { ThoxImagineClient } from './thox-imagine-node-example';

const app = express();
const client = new ThoxImagineClient();

app.use(express.json());

// Generate image endpoint
app.post('/api/generate', async (req, res) => {
  try {
    const { prompt } = req.body;

    if (!prompt) {
      return res.status(400).json({ error: 'Prompt is required' });
    }

    const result = await client.generate(prompt);

    if (!result.success) {
      return res.status(500).json({ error: result.error });
    }

    res.json({
      success: true,
      imagePath: result.imagePath,
      prompt: result.prompt,
      watermark: '© 2026 Thox.ai LLC. All Rights Reserved.',
    });

  } catch (error) {
    res.status(500).json({ error: 'Internal server error' });
  }
});

// Batch generate endpoint
app.post('/api/batch-generate', async (req, res) => {
  try {
    const { prompts } = req.body;

    if (!Array.isArray(prompts) || prompts.length === 0) {
      return res.status(400).json({ error: 'Prompts array is required' });
    }

    const results = await client.batchGenerate(prompts);

    res.json({
      success: true,
      results,
      total: results.length,
      successful: results.filter(r => r.success).length,
    });

  } catch (error) {
    res.status(500).json({ error: 'Internal server error' });
  }
});

// Get model info endpoint
app.get('/api/model-info', async (req, res) => {
  const info = await client.getModelInfo();
  res.json(info);
});

app.listen(3000, () => {
  console.log('Thox Imagine API server running on port 3000');
});
  `;

  console.log('\n📦 Express.js Integration Example:');
  console.log('─'.repeat(60));
  console.log(code);
}

// Export for use in other modules
export { ThoxImagineClient, ThoxImagineConfig, GenerateOptions, GenerationResult };

// Run examples if executed directly
if (require.main === module) {
  examples().catch(console.error);
  expressExample();
}
