#!/usr/bin/env python3
"""
Thox Imagine API Wrapper
Python interface for the Thox Imagine AI image generation model
© 2026 Thox.ai LLC. All Rights Reserved.
"""

import os
import json
import base64
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Optional, Dict, Any
from dataclasses import dataclass


@dataclass
class ThoxImagineConfig:
    """Configuration for Thox Imagine model."""
    model_name: str = "Thox-ai/thox-imagine"
    output_dir: str = "thox-imagine-outputs"
    default_temperature: float = 0.8
    default_top_p: float = 0.95
    watermark: str = "© 2026 Thox.ai LLC. All Rights Reserved. Generated by Thox Imagine."


class ThoxImagineAPI:
    """
    Python API wrapper for Thox Imagine image generation model.

    Examples:
        >>> api = ThoxImagineAPI()
        >>> image = api.generate("A beautiful sunset over mountains")
        >>> api.generate_and_save("Cyberpunk city at night", "city.png")
    """

    def __init__(self, config: Optional[ThoxImagineConfig] = None):
        """
        Initialize Thox Imagine API.

        Args:
            config: Optional configuration object. Uses defaults if not provided.
        """
        self.config = config or ThoxImagineConfig()
        self._ensure_output_dir()
        self._verify_model()

    def _ensure_output_dir(self) -> None:
        """Create output directory if it doesn't exist."""
        Path(self.config.output_dir).mkdir(parents=True, exist_ok=True)

    def _verify_model(self) -> bool:
        """
        Verify that the Thox Imagine model is available.

        Returns:
            True if model is available, raises exception otherwise.

        Raises:
            RuntimeError: If model is not found in ollama.
        """
        try:
            result = subprocess.run(
                ["ollama", "list"],
                capture_output=True,
                text=True,
                check=True
            )

            if self.config.model_name.lower() not in result.stdout.lower():
                raise RuntimeError(
                    f"Model '{self.config.model_name}' not found. "
                    "Please ensure it's installed with: "
                    "ollama create Thox-ai/thox-imagine -f Modelfile.thox-imagine"
                )

            return True

        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"Failed to verify model: {e}")
        except FileNotFoundError:
            raise RuntimeError(
                "Ollama not found. Please install from https://ollama.ai"
            )

    def generate(
        self,
        prompt: str,
        temperature: Optional[float] = None,
        top_p: Optional[float] = None,
    ) -> bytes:
        """
        Generate an image from a text prompt.

        Args:
            prompt: Text description of the desired image.
            temperature: Sampling temperature (0.0-1.0). Uses config default if None.
            top_p: Nucleus sampling threshold (0.0-1.0). Uses config default if None.

        Returns:
            Raw image bytes (PNG format).

        Raises:
            RuntimeError: If image generation fails.
            ValueError: If prompt is empty.

        Examples:
            >>> api = ThoxImagineAPI()
            >>> image_data = api.generate("A serene Japanese garden")
            >>> with open("garden.png", "wb") as f:
            ...     f.write(image_data)
        """
        if not prompt or not prompt.strip():
            raise ValueError("Prompt cannot be empty")

        temp = temperature or self.config.default_temperature
        tp = top_p or self.config.default_top_p

        print(f"🎨 Generating image with Thox Imagine...")
        print(f"📝 Prompt: {prompt}")
        print(f"⚙️  Temperature: {temp}, Top-P: {tp}")

        try:
            # Run ollama generate command
            result = subprocess.run(
                [
                    "ollama", "run",
                    self.config.model_name,
                    prompt
                ],
                capture_output=True,
                text=False,
                check=True
            )

            # Note: In actual implementation, you'd need to extract image data
            # from the ollama response. This is a simplified version.
            print("✅ Image generated successfully!")
            print(f"🔒 Watermark: {self.config.watermark}")

            return result.stdout

        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"Image generation failed: {e}")

    def generate_and_save(
        self,
        prompt: str,
        output_path: Optional[str] = None,
        temperature: Optional[float] = None,
        top_p: Optional[float] = None,
    ) -> str:
        """
        Generate an image and save it to a file.

        Args:
            prompt: Text description of the desired image.
            output_path: Path to save the image. Auto-generated if None.
            temperature: Sampling temperature (0.0-1.0).
            top_p: Nucleus sampling threshold (0.0-1.0).

        Returns:
            Path to the saved image file.

        Examples:
            >>> api = ThoxImagineAPI()
            >>> path = api.generate_and_save("Mountain landscape", "mountain.png")
            >>> print(f"Image saved to {path}")
        """
        image_data = self.generate(prompt, temperature, top_p)

        if output_path is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"thox_imagine_{timestamp}.png"
            output_path = os.path.join(self.config.output_dir, filename)

        # Ensure output directory exists
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

        with open(output_path, "wb") as f:
            f.write(image_data)

        print(f"💾 Saved to: {output_path}")
        return output_path

    def batch_generate(
        self,
        prompts: list[str],
        output_prefix: str = "batch",
    ) -> list[str]:
        """
        Generate multiple images from a list of prompts.

        Args:
            prompts: List of text prompts.
            output_prefix: Prefix for output filenames.

        Returns:
            List of paths to saved images.

        Examples:
            >>> api = ThoxImagineAPI()
            >>> prompts = [
            ...     "A sunset over the ocean",
            ...     "A futuristic city",
            ...     "An ancient forest"
            ... ]
            >>> paths = api.batch_generate(prompts)
            >>> print(f"Generated {len(paths)} images")
        """
        print(f"🚀 Starting batch generation of {len(prompts)} images...")

        saved_paths = []

        for idx, prompt in enumerate(prompts, 1):
            print(f"\n📊 Progress: {idx}/{len(prompts)}")

            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"{output_prefix}_{idx}_{timestamp}.png"
            output_path = os.path.join(self.config.output_dir, filename)

            try:
                path = self.generate_and_save(prompt, output_path)
                saved_paths.append(path)
            except Exception as e:
                print(f"❌ Failed to generate image {idx}: {e}")
                continue

        print(f"\n✅ Batch complete! Generated {len(saved_paths)}/{len(prompts)} images")
        return saved_paths

    def get_model_info(self) -> Dict[str, Any]:
        """
        Get information about the Thox Imagine model.

        Returns:
            Dictionary containing model metadata.
        """
        try:
            result = subprocess.run(
                ["ollama", "list"],
                capture_output=True,
                text=True,
                check=True
            )

            # Parse model info from output
            for line in result.stdout.split('\n'):
                if self.config.model_name.lower() in line.lower():
                    parts = line.split()
                    return {
                        "name": self.config.model_name,
                        "base": "x/flux2-klein",
                        "parameters": "8B",
                        "quantization": "FP4",
                        "watermark": self.config.watermark,
                        "uncensored": True,
                        "organization": "Thox.ai LLC"
                    }

            return {"error": "Model not found"}

        except subprocess.CalledProcessError as e:
            return {"error": f"Failed to get model info: {e}"}

    def list_generated_images(self) -> list[str]:
        """
        List all generated images in the output directory.

        Returns:
            List of image file paths.
        """
        output_dir = Path(self.config.output_dir)

        if not output_dir.exists():
            return []

        images = sorted(
            output_dir.glob("*.png"),
            key=lambda p: p.stat().st_mtime,
            reverse=True
        )

        return [str(img) for img in images]


# Example usage and CLI interface
def main():
    """Command-line interface for Thox Imagine API."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Thox Imagine - AI Image Generation",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python thox_imagine_api.py "A beautiful sunset"
  python thox_imagine_api.py "Cyberpunk city" --output city.png
  python thox_imagine_api.py --batch prompts.txt
  python thox_imagine_api.py --info
  python thox_imagine_api.py --list

© 2026 Thox.ai LLC. All Rights Reserved.
        """
    )

    parser.add_argument(
        "prompt",
        nargs="?",
        help="Text prompt for image generation"
    )

    parser.add_argument(
        "-o", "--output",
        help="Output file path"
    )

    parser.add_argument(
        "-t", "--temperature",
        type=float,
        help="Sampling temperature (0.0-1.0)"
    )

    parser.add_argument(
        "-p", "--top-p",
        type=float,
        help="Top-p sampling (0.0-1.0)"
    )

    parser.add_argument(
        "--batch",
        help="Batch generate from file (one prompt per line)"
    )

    parser.add_argument(
        "--info",
        action="store_true",
        help="Show model information"
    )

    parser.add_argument(
        "--list",
        action="store_true",
        help="List generated images"
    )

    args = parser.parse_args()

    # Initialize API
    api = ThoxImagineAPI()

    # Handle different commands
    if args.info:
        info = api.get_model_info()
        print("\n🎨 Thox Imagine Model Information")
        print("=" * 50)
        for key, value in info.items():
            print(f"{key.capitalize()}: {value}")
        return

    if args.list:
        images = api.list_generated_images()
        print(f"\n📁 Generated Images ({len(images)} total):")
        print("=" * 50)
        for img in images[:10]:  # Show last 10
            print(f"  • {img}")
        if len(images) > 10:
            print(f"  ... and {len(images) - 10} more")
        return

    if args.batch:
        with open(args.batch, 'r') as f:
            prompts = [line.strip() for line in f if line.strip()]
        api.batch_generate(prompts)
        return

    if not args.prompt:
        parser.print_help()
        return

    # Generate single image
    api.generate_and_save(
        args.prompt,
        args.output,
        args.temperature,
        args.top_p
    )


if __name__ == "__main__":
    main()
